### ISSUE TITLE
InvokeAssembly does nothing :(

### ISSUE THREAD

**Issue by rafale0n** [HavocFramework/Modules#2]
Hey, 

Thanks for looking into this.

Importing InvokeAssembly adds command `dotnet execute` but running assembly as per example does nothing. Here is the command line:
`
dotnet execute /home/pwnie/Havoc/Client/Assemblies/Rubeus.exe
`

![image](https://user-images.githubusercontent.com/77019753/195461872-e26f6eb5-8592-48b9-b4a7-a9035d252bc8.png)
Successfully imported script.

**Comment by Cracked5pider** [comment]
fixed was a client side issue.
