### ISSUE TITLE
Psexec module incorrect argument check

### ISSUE THREAD

**Issue by random-ideas** [HavocFramework/Modules#6]
In the psexec module, https://github.com/HavocFramework/Modules/blob/main/Jump-exec/Psexec/psexec.py , on line 31, the following check is performed:
`if len(param) < 3:`
However I think it should be set to either < 4 or <=3, as the later code expects to item to have 4 values (Line 37 calls param [ 3 ]).

I've done some testing and this appears to work if changed per the described. Thanks for a great project!

**Comment by S4ntiagoP** [comment]
I think I fixed this on dev: https://github.com/HavocFramework/Modules/commit/79101e2a38b5f9e773295d0619da76c9a6229ea9
let me know if you still have issues, thank you for reporting!
