### ISSUE TITLE
Incorrect paramater validation in nanorobeus when doing kerberoasting

### ISSUE THREAD

**Issue by random-ideas** [HavocFramework/Modules#7]
Hey, as per the title nanorobeus when doing a kerberoast on line 330 has the following:

`    arg1 = param[ 1 ]`

This causes it to fail when launched with 1 arg per the help file, changing it to:
`param [ 0 ]` 
Enables it to successfully run (the output is incorrect but I believe that's another issue).

**Comment by S4ntiagoP** [comment]
fixed, on dev, thank you!
